--H2 create tables

DROP TABLE IF EXISTS PAGE_WORD;
DROP TABLE IF EXISTS PAGE;

CREATE TABLE PAGE(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT
  , URL VARCHAR(255)
);

CREATE TABLE PAGE_WORD(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT
  , WORD VARCHAR(45)
  , COUNT INTEGER
  , PAGE_ID INTEGER
  , FOREIGN KEY (PAGE_ID) REFERENCES PAGE(ID)
);